# cerOS initramfs: generic (any x86_64 machine), shell-based, with the cerOS root.
hostonly="no"
add_dracutmodules+=" ceros "
omit_dracutmodules+=" systemd systemd-initrd dracut-systemd systemd-networkd network network-legacy nfs iscsi nbd lvm mdraid crypt plymouth btrfs multipath "
compress="xz"
